### PR TITLE
[wip] Update Sonic to v1.2.3

### PR DESCRIPTION
**Pull request by fpeterschmitt**
Hello :)

Just an update of the Sonic server and style changes. As i'm still working with this fork for now, the module path has changed.

Btw shouldn't i use an alias instead of changing the module name :thinking: ?

### CODE REVIEW

**Comment by OGKevin** [comment]
@Leryan Hey, thanks for the contribution. 

> Btw shouldn't i use an alias instead of changing the module name 🤔 ?

There is actually no need to change the module name. It should compile and run without the need to change it 😊.

**Comment by fpeterschmitt** [comment]
Hm yes, for a PR i guess there is no need, the problem shows when i want to use my modifications in some projects ^^

Btw i discovered something that looks like a deadlock while using this driver from inside a gRPC handler, while making a SearchQuery.

For now i switched to the other library ( https://github.com/expectedsh/go-sonic ) but if you want i can try to build a minimalist piece of code to reproduce the bug.

**Comment by OGKevin** [comment]
> Btw i discovered something that looks like a deadlock while using this driver from inside a gRPC handler, while making a SearchQuery.

Could you please indeed provide steps to reproduce. Or even make a test that triggers this deadlock. 

Could you also explain why you removed open tracing ?

**Comment by fpeterschmitt** [comment]
sorry i don't have any time for that :/ closing

**Pull request closed without merging**
